### ISSUE TITLE
Problem to change the value of local x,y and heading

### ISSUE THREAD

**Issue by hadi2f244** [navisens/NaviDocs#5]
Hi,
I want to change the value of local x,y and heading, when specific event happens(like seeing a beacon or by map data). 
I tried some functions like setCartesianOffsetInMeters and setLocalHeadingOffsetInDegrees, but they don’t work as i want and are confusing too! 
setLocationLatitudeLongitude() doesn’t work too, it transfers the marker to the beggining and reset the value of heading.
Is there any way to do this?!

Thanks.

**Comment by lucasnavisens** [comment]
Hi hadi2f244,

Can you tell me what version of the SDK are you using ?

So as specified in the docs:
setCartesianOffsetInMeters: Adds an offset to both x and y axes, which means if your current
XY is (0,0) and you call this method with (5,5) then the SDK's internal XY will be offset by 5 meters in X and 5 meters in Y.
However if your current XY is (5, 3) and you call the offset method with (5, 5) then the internal XY
set will be (10, 8). They are offsets to our coordinate frames, so if you which to set an XY position
right now the solution would be to call [resetLocalEstimation](https://github.com/navisens/NaviDocs/blob/master/API.iOS.md#resetlocalestimation
), and then set the XY Offset with setCartesianOffsetInMeters.

I will add a method to the next SDK push that wraps these two systems to be able to set an XY directly without requiring you call resetLocalEstimation.

Then for the setLocalHeadingOffsetInDegrees: the headings you input are cumulative for the 
rotations to be correct, so if you want to set the actual heading of the estimation, you actually need to
calculate the difference between the SDK [local_heading](https://github.com/navisens/NaviDocs/blob/master/API.iOS.md#getlocation---location) you are receiving and the heading you want to set and input the result of the angular difference in the setLocalHeadingOffsetInDegrees, and this should fix your problem. (Also make sure you are respecting the heading frames we are using as a counterclockwise rotation in degrees)

If you wish to reset the heading you can call: [resetLocalHeading](https://github.com/navisens/NaviDocs/blob/master/API.iOS.md#resetlocalheading).

And since the local_heading in the SDK will be 90 you will be able to rotate using the absolute value you input and not an offset from the current local_heading, however I do recommend using the offset system as the internal rotations for our inertial trajectory are handled out of the box in our SDK.

Let me know if you have any more questions.
Cheers.

**Comment by hadi2f244** [comment]
Thank you for your reply. I test it,now i can move the marker with setCartesianOffsetInMeters function, but i think to changing the heading by setLocalHeadingOffsetInDegrees function doesn't work properly alongside setCartesianOffsetInMeters. I checked this issue in the below code. 

```
if(an event){
        localOffsetX += 0;
        localOffsetY += 3;
        core.getMotionDna().setCartesianOffsetInMeters(localOffsetX, localOffsetY);
        localOffsetH += 90;
        core.getMotionDna().setLocalHeadingOffsetInDegrees(90);
}
```
I saved last coordinate frames state in localOffsetX,localOffsetX and localOffsetH. When specific event accured (like seeing a beacon), marker will be offset 5 meters in Y axis and then 90 degrees in the heading. So if it start from 0,0 with 0 heading, The movement path expected to be something like this, but it doesn't!(I just hold the beacon and walked in the inial X axis)
![img_20180717_084609](https://user-images.githubusercontent.com/3657394/42797549-face571c-89a4-11e8-8050-52ce486198f9.jpg)
I show the coordinate heading with red, 5 meters offset in Y by blue and the usuall movements(in the inial X axis) with black color.

My phone screen records were uploaded to show real outputs. I change the pointer heading according to localOffsetH by calling js function from android, it works good as expected unlike local x,y and heading. 
![20180710_235230](https://user-images.githubusercontent.com/3657394/42797664-6bce8cb6-89a5-11e8-856c-4b19957c73ce.gif)
![20180710_234740](https://user-images.githubusercontent.com/3657394/42797686-8671a512-89a5-11e8-8747-43ab0f2ea8d4.gif)

As you see in the videos,the pointer heading work well but setCartesianOffsetInMeters & setLocalHeadingOffsetInDegrees don't work properly. I check these functions separatly, they work fine but they can't be use simultaneously.

**Comment by lucasnavisens** [comment]
Hey,

Seems that what you are doing isn't working since you are not calling `resetLocalEstimation` before any local transform, which should reset all our rotation/position accumulators.

However, I think you should just wait for our next SDK update (next Friday) which will have an API revamp for local transformations which will allow you to achieve what you are trying to do very easily without any real transformation work on your side.

Let me know if you have any questions,
Cheers.

**Comment by lucasnavisens** [comment]
Hey !

Hope all is well!
We just updated our SDK (v1.6), so you can now use both methods:
This one to set the position in XY:
https://github.com/navisens/NaviDocs/blob/master/API.iOS.md#setcartesianpositionx_-x-double-y-y-double

And this one to set the heading in degrees:
https://github.com/navisens/NaviDocs/blob/master/API.Android.md#void-setlocalheadingdouble-heading

This should fix your initialization problems.
Cheers.
Let me know how it goes.

**Comment by hadi2f244** [comment]
Hi lucas

I follow the repo every day! I checked new version. Thank you for the mention. 

I found some new errors when i tested my app on another cellphones:

1.
07-26 17:06:30.816 27667-27851/com.test.test.combined W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
07-26 17:06:30.816 27667-27851/com.test.test.combined W/System.err:     at com.navisens.motiondnaapi.MyJni.getCpuUsage(MyJni.java:191)
It happens in some cellphones like Lg G3(android 5.1.1).( I checked the demo app on play store, it works fine on G3!). 

2.
I found the sdk very slow on nokia3(android 8.1), it works on android 7 but this issue happened when i updated it to 8.1 . I checked my code, it worked fine and receiveMotion callback called normally but the state values(x,y and heading) changed very slowly. I think it relates to above error, too.

3.
I use Navibeacon to scan beacons. In some cellphones, it not working well or collapses! Sometimes it not working for 8 seconds or it sticks forever! Some times beacon callback calls very much and motionDNA can’t works alongside it (lg G3). After i changed scan period from 100ms to 300ms it worked but it was very slow and i think because of BLE scanning uncertainty, sometimes it’s needed to scan beacons with 100ms period(i checked the Between period too, it doesn’t effect) 

Another problem with navibeacon is that developers can work with just one received beacon signal in every callback calling. I tested altbeacon library, it works fine and user can see all of the seen beacons at once. So i think Navibeacon class must be redesign.

4. 
In some cases there are some battery saving modes on cellphones(like Xiaomi devices)and default option is the battery saving mode that Motiondna and Navibeacon not working well on this cases. It will be so exciting that developers can control it from Navis sdk.

5.
I checked low power battery usage mode, But i couldn’t sense battery usage improvement in my tests. So it’ll be helpful that battery usage benchmarks provided. Besides there are some parameters that effect battery usage like callback period, performance mode, battery usage mode. It’s confusing that how to set them for battery usage improvement.

I try to explain my problems that i meet in my last three weeks working on Navisens.
